export interface StatesGraph {
	[key: string]: string[];
}

// prettier-ignore
export const statesGraph: StatesGraph = {
    Alabama: ["Tennessee", "Georgia", "Florida", "Mississippi"],
    Arizona: ["California", "Nevada", "Utah", "Colorado", "New Mexico"],
    Arkansas: [
      "Missouri",
      "Tennessee",
      "Mississippi",
      "Louisiana",
      "Texas",
      "Oklahoma",
    ],
    California: ["Oregon", "Nevada", "Arizona"],
    Colorado: [
      "Wyoming",
      "Nebraska",
      "Kansas",
      "Oklahoma",
      "New Mexico",
      "Arizona",
      "Utah",
    ],
    Connecticut: ["New York", "Massachusetts", "Rhode Island"],
    Delaware: ["Maryland", "New Jersey", "Pennsylvania"],
    Florida: ["Alabama", "Georgia"],
    Georgia: [
      "Tennessee",
      "North Carolina",
      "South Carolina",
      "Florida",
      "Alabama",
    ],
    Idaho: ["Montana", "Wyoming", "Utah", "Nevada", "Oregon", "Washington"],
    Illinois: ["Wisconsin", "Iowa", "Missouri", "Kentucky", "Indiana"],
    Indiana: ["Michigan", "Ohio", "Kentucky", "Illinois"],
    Iowa: [
      "Minnesota",
      "Wisconsin",
      "Illinois",
      "Missouri",
      "Nebraska",
      "South Dakota",
    ],
    Kansas: ["Nebraska", "Missouri", "Oklahoma", "Colorado"],
    Kentucky: [
      "Illinois",
      "Indiana",
      "Ohio",
      "West Virginia",
      "Virginia",
      "Tennessee",
      "Missouri",
    ],
    Louisiana: ["Arkansas", "Mississippi", "Texas"],
    Maine: ["New Hampshire"],
    Maryland: ["Virginia", "West Virginia", "Pennsylvania", "Delaware"],
    Massachusetts: [
      "New York",
      "Vermont",
      "New Hampshire",
      "Rhode Island",
      "Connecticut",
    ],
    Michigan: ["Ohio", "Indiana", "Wisconsin"],
    Minnesota: ["North Dakota", "South Dakota", "Iowa", "Wisconsin"],
    Mississippi: ["Tennessee", "Alabama", "Louisiana", "Arkansas"],
    Missouri: [
      "Iowa",
      "Nebraska",
      "Kansas",
      "Oklahoma",
      "Arkansas",
      "Tennessee",
      "Kentucky",
      "Illinois",
    ],
    Montana: ["North Dakota", "South Dakota", "Wyoming", "Idaho"],
    Nebraska: [
      "South Dakota",
      "Iowa",
      "Missouri",
      "Kansas",
      "Colorado",
      "Wyoming",
    ],
    Nevada: ["Oregon", "Idaho", "Utah", "Arizona", "California"],
    "New Hampshire": ["Maine", "Massachusetts", "Vermont"],
    "New Jersey": ["New York", "Pennsylvania", "Delaware"],
    "New Mexico": ["Arizona", "Colorado", "Oklahoma", "Texas"],
    "New York": [
      "Vermont",
      "Massachusetts",
      "Connecticut",
      "New Jersey",
      "Pennsylvania",
    ],
    "North Carolina": ["Virginia", "Tennessee", "Georgia", "South Carolina"],
    "North Dakota": ["Minnesota", "South Dakota", "Montana"],
    Ohio: ["Michigan", "Indiana", "Kentucky", "West Virginia", "Pennsylvania"],
    Oklahoma: [
      "Kansas",
      "Missouri",
      "Arkansas",
      "Texas",
      "New Mexico",
      "Colorado",
    ],
    Oregon: ["Washington", "Idaho", "Nevada", "California"],
    Pennsylvania: [
      "New York",
      "New Jersey",
      "Delaware",
      "Maryland",
      "West Virginia",
      "Ohio",
    ],
    "Rhode Island": ["Massachusetts", "Connecticut"],
    "South Carolina": ["North Carolina", "Georgia"],
    "South Dakota": [
      "North Dakota",
      "Minnesota",
      "Iowa",
      "Nebraska",
      "Wyoming",
      "Montana",
    ],
    Tennessee: [
      "Kentucky",
      "Virginia",
      "North Carolina",
      "Georgia",
      "Alabama",
      "Mississippi",
      "Arkansas",
      "Missouri",
    ],
    Texas: ["New Mexico", "Oklahoma", "Arkansas", "Louisiana"],
    Utah: ["Idaho", "Wyoming", "Colorado", "Arizona", "Nevada"],
    Vermont: ["New York", "New Hampshire", "Massachusetts"],
    Virginia: [
      "Maryland",
      "West Virginia",
      "Kentucky",
      "Tennessee",
      "North Carolina",
    ],
    Washington: ["Oregon", "Idaho"],
    "West Virginia": ["Ohio", "Pennsylvania", "Maryland", "Virginia", "Kentucky"],
    Wisconsin: ["Michigan", "Minnesota", "Iowa", "Illinois"],
    Wyoming: ["Montana", "South Dakota", "Nebraska", "Colorado", "Utah", "Idaho"],
  };
